In [1]:
# Installing for the first time
# pip install numpy -> in terminal

In [2]:
# Importing numpy
import numpy as np # we name it as np

# Numpy
- Numpy are like lists, Lists are best for short codes
- But numpy are much faster than lists
- Same datatype, Lists are different datatype
- Store data very compactly
- Great for big numerical operations
- Consumes less memory and is convenient to use

### Using numpy to create arrays

In [8]:
# Creating 1D Array
a = np.array([2,4,-3])
print(a)

[ 2  4 -3]


In [7]:
# Creating 2D Array with two square brackets
b = np.array([[2, 4, 3, -7]])
print(b)

[[ 2  4  3 -7]]


In [11]:
# Checking its type
type(a)
type(b)
# n dimensional Array

numpy.ndarray

In [12]:
# Creating lists of lists -> 2D Array - Matrix
c = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(c)

[[2 2 2]
 [3 3 3]
 [4 4 4]]
