# Array Functions

In [2]:
import numpy as np
a = np.array([10,12,15,2,5,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   5. ,   4. ,   6. , 100. , 320. ,
         0.5,  10.3])

In [3]:
a.sort()
a

array([  0.5,   2. ,   4. ,   5. ,   6. ,  10. ,  10.3,  12. ,  15. ,
       100. , 320. ])

In [5]:
b = np.array([10.2,3.4,53.6,91.6,45.4])
b

array([10.2,  3.4, 53.6, 91.6, 45.4])

In [8]:
c = np.concatenate((a, b))

In [10]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   5. ,   6. ,  10. ,  10.2,  10.3,
        12. ,  15. ,  45.4,  53.6,  91.6, 100. , 320. ])

## 2-D Arrays

In [24]:
a = np.array([[1,2], [5,4]]) # Two axis
a

array([[1, 2],
       [5, 4]])

In [25]:
b = np.array([[6,7], [8,9]])
b

array([[6, 7],
       [8, 9]])

In [26]:
c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [ ]:
# The dimensions should be same or else we use
# column_stack or axis=1

In [27]:
np.concatenate((a,b), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

## 3-D Array

In [31]:
a = np.array([[[0,1,2,3], [4,5,6,7]], [[0,1,2,3], [4,5,6,7]], [[0,1,2,3], [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [32]:
# To find the number of dimensions
a.ndim

3

In [34]:
b = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
b.ndim

2

In [36]:
# To check the size -> (no. of elements)
a.size

24

In [39]:
a.shape # 3 -> dimensions, 2 -> rows, 4 -> cols

(3, 2, 4)

In [48]:
a = np.arange(9) # 3*3 = 9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
# Reshape
a = a.reshape(3, 3) # 3*3
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [58]:
# convert 1-D into 2-D Array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.shape

(9,)

In [61]:
# Row wise 2-D conversion
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
b.shape

(1, 9)

In [63]:
# Column wise 2-D conversion
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a[2:6]

array([3, 4, 5, 6])

In [66]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [67]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a + 6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
a * 6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [70]:
a.sum()

45

In [71]:
a.mean()

5.0