## Vector
- A vector is an array with a single dimension (1D) (no difference between rows and columns)

## Matrix
- It refers to an array with two dimensions (2D)

## 1D Array

In [2]:
import numpy as np
a = np.array([5, 4, 3])
a

array([5, 4, 3])

In [3]:
len(a) # to know the array's length

3

In [4]:
a[0] # to get the first index value

5

In [5]:
a[0:] # to get the values through slicing

array([5, 4, 3])

## 2D Array

In [8]:
# Lists of lists
# b = np.array([3, 3, 3], [4, 4, 4], [5, 5, 5]) # it will give us an error becuase of 1D
b = np.array([[3, 3, 3], [4, 4, 4], [5, 5, 5]]) 
b

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [9]:
len(b) # values are 3

3

In [10]:
b[0]

array([3, 3, 3])

In [11]:
b[:0]

array([], shape=(0, 3), dtype=int64)

## 3D Array

- For 3-D higher dimensional arrays, the term Tensor is commonly used.
- The Tensor Flow is an open-source Python library used for Machine Learning and Artificial Intelligence

### Array attrributes
- Dimensions are called axis 
  - 1 axis x-axis only -> 1D
  - 2 axis x-axis, y-axis -> 2D

## How to create an array using Numpy
### 1-D

In [4]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([0., 0.])

In [ ]:
b = np.zeros(2)
b

In [5]:
c = np.ones(3)
c

In [6]:
# Create an empty array with 2 elements
d = np.empty(3)
d

array([3., 2., 1.])

In [7]:
# with range of elements
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [8]:
# with specific range of elements
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [9]:
# continue
g = np.arange(2, 20, 2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# linearly spaced arrays
h = np.linspace(0, 10, num=5) # gives us 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
# speicific datatypes array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [14]:
j = np.ones(5, dtype=np.float64)
j

array([1., 1., 1., 1., 1.])

### 2-D

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3-D Array

In [20]:
# making and reshaping a 3D array
k = np.arange(24).reshape(2, 3, 4) # 2 -> 2D, 3 -> rowa, 4 -> cols.
k

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])